import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Header from "../components/ui/Header";
import NewLabForm from "../components/ui/home/NewLabform";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>PeerLab</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="mx-auto max-w-[1200px]">
        <header className="p-10">
          <h1 className="text-3xl sm:text-4xl md:text-5xl font-semibold ">
            Instant Discussions, Experiements, Brainstorming Ideas and so on.
          </h1>
          <p></p>
        </header>
        <div className="p-10 flex flex-col  justify-center items-center gap-2">
          <NewLabForm />
        </div>
      </main>
    </>
  );
};

export default Home;
